update to User interface to see an accept invitations
jcabi/jcabi-github pull request #1514
Opened 2020-01-20 22:30 UTC by ShalomGottesman

This request is a correction to a previous one that had extra code and missed annotations. see #1513

2020-01-20 22:33 UTC, 0crat commented
Job [#1514](https://github.com/jcabi/jcabi-github/issues/1514) is now in scope, role is `REV`

<!-- https://www.0crat.com/footprint/C9R53K5JA/48bd9de3-e3b3-4bc2-a177-1229ed15e9b9, version: 0.50.40, hash: ${buildNumber} -->

2020-01-21 03:55 UTC, ShalomGottesman commented
I learned that if I push more updates to the same branch that already has a pull request, then the new commits are added to that request. My apologies for making two requests into one. Next time I will open a separate branch if I want to request two commits be added.

2020-01-21 08:55 UTC, amihaiemil commented
@ShalomGottesman I don't really understand, this PR looks almost the same as the initial one :D 
You can just fix that PR and it's ok.

2026-06-18 20:10 UTC, edmoffo requested changes
The change adds two interface methods and an implementation on the Smart inner class, but several issues block merging. Four inline notes below cover a correctness bug in invitations(), a missing test, indentation that does not match the rest of the file, and dead body() calls on GET requests.

2026-06-18 20:10 UTC, edmoffo commented on src/main/java/com/jcabi/github/User.java
> +					    	invite.getJsonObject("owner").getString("login")
Arguments are swapped. Coordinates.Simple takes (user, repo), so this should be (owner.login, name), not (name, owner.login). The current order yields coordinates whose user() returns the repo name.

2026-06-18 20:10 UTC, edmoffo commented on src/main/java/com/jcabi/github/User.java
> +					.body().back()
body().back() on a GET adds nothing. Drop the body() call here and in invitations() above; the request is already a GET and the body builder is no longer setting any payload.

2026-06-18 20:10 UTC, edmoffo commented on src/main/java/com/jcabi/github/RtRepo.java
> +    public Iterable<String> invitees() throws IOException {
No test covers RtRepo.invitees(). Add an RtRepoTest case that mocks the /invitations endpoint with MkContainer and asserts the parsed login set, otherwise the parsing of invitee.login is unverified.

2026-06-18 20:10 UTC, edmoffo commented on src/main/java/com/jcabi/github/RtRepo.java
> +			invitees.add(val.getJsonObject("invitee").getString("login"));
Indentation in this method mixes tabs and spaces. The rest of the file uses four-space indent only; please normalize to match before merge.

2026-08-03 09:09 UTC, yegor256 commented
Please forgive us for closing this pull request without merging it. It has developed merge conflicts with the current `master` branch and has been open for more than a month, so we are closing it as part of routine maintenance.

This is no reflection on the value of your contribution, @ShalomGottesman. If you are still interested, please consider submitting a new pull request with the same idea, rebased against the current master, taking into account whatever has changed there since. We would welcome it.

2026-08-03 09:09 UTC, closed without merging